name = "siren"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true

[[kv_namespaces]]
binding = "SIREN"
id = "a8753e6a7e624f3d8e05f29eedf7378f"

[build]
command = "RUSTFLAGS='-C target-feature=+bulk-memory' cargo install worker-build --force && worker-build --release"

[env.dev]
build = { command = "RUSTFLAGS='-C target-feature=+bulk-memory' cargo install worker-build --force && worker-build --dev" }

[vars]
UUID = "f282b878-8711-45a1-8c69-5564172123c1"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/FoolVPN-ID/Siren/refs/heads/master/web/index.html"
SUB_PAGE_URL  = "https://raw.githubusercontent.com/FoolVPN-ID/Siren/refs/heads/master/web/sub.html"
