name: cf workers

on:
  workflow_dispatch:

  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: cf

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Cache Cargo
      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      # Install Rust
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      # Install worker-build (Rust → WASM builder)
      - name: Install worker-build
        run: cargo install worker-build --force

      # Build Rust WASM dengan bulk-memory
      - name: Build with bulk-memory
        run: |
          RUSTFLAGS="-C target-feature=+bulk-memory" \
          worker-build --release

      # Deploy ke Cloudflare (skip wasm-opt bawaan Wrangler)
      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        env:
          NO_WASM_OPT: 1
