name: cf workers

on:
  workflow_dispatch:

  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: cf

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Rust
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      # Install worker-build (Rust → WASM builder)
      - name: Install worker-build
        run: cargo install worker-build --force

      # Build Rust WASM dengan bulk-memory enabled (fix error memory.copy)
      - name: Build with bulk-memory
        run: |
          RUSTFLAGS="-C target-feature=+bulk-memory" \
          worker-build --release

      # Deploy ke Cloudflare
      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
